services:
  app: 
    image: php-docker-example
    build: 
      dockerfile: ./docker/app/Dockerfile
    container_name: php-docker-example-app
    restart: always
    volumes:
      - ./app:/var/www
  nginx:
    image: nginx:1.27-alpine
    container_name: php-docker-example-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./app/public:/var/www/public
      - ./docker/nginx:/etc/nginx/conf.d
  database:
    image: mariadb:11.5
    container_name: php-docker-example-database
    restart: unless-stopped
    ports: 
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_USER: user
      MARIADB_PASSWORD: secret
      MARIADB_DATABASE: php_docker_example

volumes:
  database_data:
