services:
  app: 
    image: php-docker-example
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: php-docker-example-app
    restart: always
    working_dir: /var/www
    volumes:
      - ./src:/var/www
  nginx:
    image: nginx:1.27.1-alpine
    container_name: php-docker-example-nginx
    restart: always
    ports:
      - 8001:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
